const { z } = require('zod')

exports.salesValidation = z.object({
  date_sale: z.string(),
  turn: z.number(),
  vendor: z.string(),
  over: z.number().optional(),
  fault: z.number().optional(),
  cash: z.number().optional(),
  credit_card: z.number().optional(),
  debit_cart: z.number().optional(),
  pix: z.number().optional(),
  promissory: z.number().optional(),
  payment: z.number().optional(),
  tobacco: z.number().optional(),
  total_sale: z.number().optional(),
  rent_part: z.number().optional(),
  carlton_part: z.number().optional(),
  purchase_part: z.number().optional(),
  contabilitie_part: z.number().optional(),
  thirteenth_part: z.number().optional(),
  energetic_part: z.number().optional(),
  energy_part: z.number().optional(),
  gudang_part: z.number().optional(),
  tax_part: z.number().optional(),
  ticket_part: z.number().optional(),
  salary_part: z.number().optional(),
  security_part: z.number().optional(),
  icecream_part: z.number().optional(),
  total_geral_part: z.number().optional(),
})
