-- CreateTable
CREATE TABLE "Sales" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "date_sale" TEXT NOT NULL,
    "turn" INTEGER NOT NULL,
    "vendor" TEXT NOT NULL,
    "over" REAL,
    "fault" REAL,
    "cash" REAL,
    "credit_card" REAL,
    "debit_cart" REAL,
    "pix" REAL,
    "promissory" REAL,
    "payment" REAL,
    "tobacco" REAL,
    "total_sale" REAL NOT NULL,
    "rent_part" REAL,
    "carlton_part" REAL,
    "purchase_part" REAL,
    "contabilitie_part" REAL,
    "thirteenth_part" REAL,
    "energetic_part" REAL,
    "energy_part" REAL,
    "gudang_part" REAL,
    "tax_part" REAL,
    "ticket_part" REAL,
    "salary_part" REAL,
    "security_part" REAL,
    "icecream_part" REAL,
    "total_geral_part" REAL
);
